# Generated by Django 4.2 on 2023-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file3D',
            field=models.FileField(blank=True, upload_to='photos/file3D'),
        ),
    ]
