# Generated by Django 4.2 on 2023-06-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_file3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file3D',
            field=models.FileField(blank=True, default=None, upload_to='photos/file3D'),
        ),
    ]
