# Generated by Django 4.2 on 2023-06-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='prodict',
            new_name='product',
        ),
    ]
