# Generated by Django 4.2 on 2023-06-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_prodict_reviewrating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model3d_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='model_offset_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='model_offset_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='model_offset_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='model_scale_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('G', 'Glasses'), ('C', 'Collar'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
