# Generated by Django 4.2 on 2023-06-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_model3d_url_product_model_offset_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model3d_url',
            field=models.CharField(max_length=200),
        ),
    ]
