# Generated by Django 4.2 on 2023-09-29 17:12

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_model3d_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=djrichtextfield.models.RichTextField(max_length=500, null=True),
        ),
    ]
