# Generated by Django 4.2 on 2023-05-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
